package com.mzielu.storeissue

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.mzielu.storeissue.ui.main.MainFragment

//default starting file generated by Android Studio
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_activity)
        if (savedInstanceState == null) {
            supportFragmentManager.beginTransaction()
                .replace(R.id.container, MainFragment.newInstance())
                .commitNow()
        }
    }
}